### ISSUE TITLE
Missing patient_100_dataset.pkl 

### ISSUE THREAD

**Issue by lawkaho** [MertDuman/Zero-Shot-ECG#1]
FileNotFoundError: [Errno 2] No such file or directory: '..\\dataset_training\\dataset_beat_trios_domain_adapted\\patient_100_dataset.pkl'

Sorry,I don't know how to get this pkl 
And , After run ecg_beat_extraction.ipynb twice , i can not get 6 files (just 3 in dataset_beats)
I think i don't know how to get the  beat-trios

**Comment by MertDuman** [comment]
Hi,
When you run ecg_beat_extraction.ipynb a second time, you should set `beat_trio=True` as commented in the notebook. Also, don't forget to change the name of the output files at the end of the notebook to reflect that they are now beat trios.
